//! # met-protocol
//!
//! Typed, panic-free parser for the line-based UART protocol between the
//! ESP32 (`EspressoFirmware`) and the machine backend.
//!
//! This crate is **pure**: no IO, no globals, no async. It is the phase-1
//! extraction of `esp_serial/data.py` plus the line dispatch from
//! `machine.py`, and it is held to byte-for-byte parity with the Python
//! implementation by the golden test suite in `tests/golden.rs`
//! (fixtures generated by `met-core/tools/gen_goldens.py`).
//!
//! Parity ground rules:
//! - Where Python parses successfully, we produce the same value and the
//!   same socket.io JSON.
//! - Where Python logs-and-returns-`None`, we return `None`.
//! - Where Python raises an *uncaught* exception (crashing the read loop —
//!   the bug class this rewrite removes), we return `None` gracefully.
//!   These cases are marked `raises` in the golden files.

pub mod button;
pub mod esp_info;
pub mod heater;
pub mod log;
pub mod message;
pub mod notify;
pub mod pynum;
pub mod sensor;
pub mod shot;

pub use button::{ButtonEvent, ButtonEventData};
pub use esp_info::EspInfo;
pub use heater::HeaterTimeoutInfo;
pub use log::EspLog;
pub use message::{
    has_crash_marker, is_boot_banner, parse_line, EspMessage, LineKind, ParsedLine,
    BARE_BUTTON_TOKENS,
};
pub use notify::MachineNotify;
pub use pynum::PyFloat;
pub use sensor::SensorData;
pub use shot::{MachineState, ShotData};
